
name: Publish to Docker Hub

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Setup Environment
        run: sudo apt-get install -y curl jq

      - name: Get changed directories
        id: getchange
        run: |
          LAST_COMMIT=$(git rev-parse HEAD~1 2>/dev/null)
          if [ -z "$LAST_COMMIT" ]; then
            # If there's no commit to compare with, compare the current commit with an empty tree
            LAST_COMMIT=4b825dc642cb6eb9a060e54bf8d69288fbee4904
          fi
          echo "::set-output name=dirs::$(git diff --dirstat=files,0 $LAST_COMMIT..HEAD | awk '{print $2}')"

      - name: Bundle and send changes
        env:
          KUBIYA_API_KEY: ${{ secrets.KUBIYA_API_KEY }}
        run: |
          for dir in ${{ steps.getchange.outputs.dirs }}; do
            if [ -d "$dir" ]; then
              tar -czf changes.tar.gz $dir
              ENCODED_CONTENT=$(base64 -w 0 changes.tar.gz)
              curl -X POST https://api.kubiya.ai/api/v1/function/function_builder \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${KUBIYA_API_KEY}" \
              -d "{
                \"action\": \"build_from_json\",
                \"input\": {
                  \"image\": \"kubiya/action-store-$dir\",
                  \"source_context\": \"$ENCODED_CONTENT\"
                }
              }"
            fi
          done
